apiVersion: v1
kind: Template
message: 'Login to TestLink with the default admin user: admin/admin'
metadata:
  annotations:
    description: The TestLink OpenShift template
    tags: 'instant-app,testlink'
  name: testlink
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: testlink
      name: testlink
    spec:
      ports:
        - name: testlink
          port: 9000
          protocol: TCP
          targetPort: 9000
      selector:
        app: testlink
        deploymentconfig: testlink
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      annotations:
        description: Route for TestLink's http service.
      labels:
        app: testlink
      name: testlink
    spec:
      port:
        targetPort: testlink
      tls:
        termination: edge
      to:
        kind: Service
        name: testlink
  - apiVersion: v1
    data:
      username: YWRtaW4=
    kind: Secret
    labels:
        app: testlink
    metadata:
      annotations:
        template.openshift.io/base64-expose-password: '{.data[''password'']}'
      name: testlink-admin-password
    stringData:
      password: ${TESTLINK_ADMIN_PASSWORD}
    type: kubernetes.io/basic-auth    
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: testlink
      name: testlink
    spec:
      tags:
        - annotations:
            description: The TestLink Docker image
            tags: testlink
          from:
            kind: DockerImage
            name: 'bitnami/testlink:1'
          importPolicy: {}
          name: '1'
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: testlink
        deploymentconfig: testlink
      name: testlink
    spec:
      replicas: 1
      selector:
        app: testlink
        deploymentconfig: testlink
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/container.testlink.image.entrypoint: '["./bin/run.sh"]'
          creationTimestamp: null
          labels:
            app: testlink
            deploymentconfig: testlink
        spec:
          containers:
            - env:
                - name: SONARQUBE_JDBC_PASSWORD
                  value: '${POSTGRESQL_PASSWORD}'
                - name: SONARQUBE_JDBC_URL
                  value: 'jdbc:postgresql://postgresql-testlink/sonar'
                - name: SONARQUBE_JDBC_USERNAME
                  value: sonar
              volumeMounts:
                - mountPath: /opt/testlink/data
                  name: sonar-data
                  subPath: data
                - mountPath: /opt/testlink/logs
                  name: sonar-logs
                  subPath: logs
                - mountPath: /opt/testlink/temp
                  name: sonar-temp
                  subPath: temp
                - mountPath: /opt/testlink/extensions/plugins
                  name: sonar-plugins
                  subPath: plugins      
              image: ' '
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 9000
                initialDelaySeconds: 60
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 5
              name: testlink
              ports:
                - containerPort: 9000
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 9000
                initialDelaySeconds: 60
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 5
              resources:
                limits:
                  cpu: 1
                  memory: 4Gi
                requests:
                  cpu: 500m
                  memory: 2Gi
              terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - emptyDir: {}
              name: sonar-data
            - emptyDir: {}
              name: sonar-logs
            - emptyDir: {}
              name: sonar-temp
            - name: sonar-plugins
              persistentVolumeClaim:
                claimName: testlink-data
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - testlink
            from:
              kind: ImageStreamTag
              name: 'testlink:${SONARQUBE_VERSION}'
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: testlink
      name: postgresql-testlink
    spec:
      ports:
        - name: postgresql
          port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        app: testlink
        deploymentconfig: postgresql-testlink
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: testlink
        deploymentconfig: postgresql-testlink
      name: postgresql-testlink
    spec:
      replicas: 1
      selector:
        app: testlink
        deploymentconfig: postgresql-testlink
      strategy:
        recreateParams:
          timeoutSeconds: 600
        resources: {}
        type: Recreate
      template:
        metadata:
          labels:
            app: testlink
            deploymentconfig: postgresql-testlink
        spec:
          containers:
            - env:
                - name: POSTGRESQL_USER
                  value: sonar
                - name: POSTGRESQL_PASSWORD
                  value: '${POSTGRESQL_PASSWORD}'
                - name: POSTGRESQL_DATABASE
                  value: sonar
              image: ' '
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 30
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 5432
                timeoutSeconds: 1
              name: postgresql
              ports:
                - containerPort: 5432
                  protocol: TCP
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - '-i'
                    - '-c'
                    - >-
                      psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d
                      $POSTGRESQL_DATABASE -c 'SELECT 1'
                failureThreshold: 3
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              volumeMounts:
                - mountPath: /var/lib/pgsql/data
                  name: postgresql-data
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: postgresql-data
              persistentVolumeClaim:
                claimName: postgresql-testlink-data
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - postgresql
            from:
              kind: ImageStreamTag
              name: 'postgresql:9.5'
              namespace: openshift
          type: ImageChange
        - type: ConfigChange
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: testlink
      name: postgresql-testlink-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: ${POSTGRESQL_PERSISTENT_VOLUME_CLASS}
      resources:
        requests:
          storage: '${POSTGRESQL_VOLUME_CAPACITY}'
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: testlink
      name: testlink-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: ${SONAR_PERSISTENT_VOLUME_CLASS}
      resources:
        requests:
          storage: '${SONAR_VOLUME_CAPACITY}'
parameters:
  - displayName: TestLink version
    name: SONARQUBE_VERSION
    required: true
    value: '7.9.1'
  - description: Password for TestLink Server PostgreSQL backend
    displayName: TestLink's PostgreSQL Password
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    name: POSTGRESQL_PASSWORD
    required: true
  - description: Password for TestLink Admin
    displayName: TestLink's Admin Password
    from: '[a-zA-Z0-9]{8}'
    generate: expression
    name: TESTLINK_ADMIN_PASSWORD
    required: true  
  - description: Volume space available for PostgreSQL
    displayName: PostgreSQL Volume Capacity
    name: POSTGRESQL_VOLUME_CAPACITY
    required: true
    value: 20Gi
  - description: Volume space available for TestLink
    displayName: TestLink Volume Capacity
    name: SONAR_VOLUME_CAPACITY
    required: true
    value: 5Gi
  - name: SONAR_PERSISTENT_VOLUME_CLASS
    displayName: Persistent Volume Class name
    description: The class of the volume; netapp-file-standard
    required: false
    value: netapp-file-standard
  - name: POSTGRESQL_PERSISTENT_VOLUME_CLASS
    displayName: Persistent Volume Class name
    description: The class of the volume; netapp-file-standard
    required: false
    value: netapp-file-block
   